#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x597240FE94E60165 (rbtcollins@hp.com)
#
Name     : deprecated-python-mock
Version  : 2.0.0
Release  : 67
URL      : http://pypi.debian.net/mock/mock-2.0.0.tar.gz
Source0  : http://pypi.debian.net/mock/mock-2.0.0.tar.gz
Source99 : http://pypi.debian.net/mock/mock-2.0.0.tar.gz.asc
Summary  : Rolling backport of unittest.mock for all Pythons
Group    : Development/Tools
License  : BSD-2-Clause
Requires: deprecated-python-mock-license = %{version}-%{release}
Requires: deprecated-python-mock-python = %{version}-%{release}
Requires: funcsigs
Requires: pbr
Requires: six
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pbr-legacypython
BuildRequires : setuptools
BuildRequires : setuptools-legacypython
BuildRequires : six

%description
mock is a library for testing in Python. It allows you to replace parts of
your system under test with mock objects and make assertions about how they
have been used.

%package legacypython
Summary: legacypython components for the deprecated-python-mock package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-python-mock package.


%package license
Summary: license components for the deprecated-python-mock package.
Group: Default

%description license
license components for the deprecated-python-mock package.


%package python
Summary: python components for the deprecated-python-mock package.
Group: Default

%description python
python components for the deprecated-python-mock package.


%prep
%setup -q -n mock-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554327123
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-python-mock
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-python-mock/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-python-mock/LICENSE.txt

%files python
%defattr(-,root,root,-)
